// Extracted prose className constants (audit #432 item 18 P2.5): the
// scene-message and channel-status blobs had grown past ~1100 chars inline.
// Values are byte-identical to the inline originals — pure extraction, no
// token migration inside them (amber has no semantic alias; parchment is
// already semantic).
export const proseParchment =
  'max-w-2xl w-full text-center font-serif text-parchment-ink dark:text-parchment-ink-dark prose dark:prose-invert prose-p:text-parchment-ink dark:prose-p:text-parchment-ink-dark prose-headings:text-parchment-ink-strong dark:prose-headings:text-parchment-ink-strong-dark prose-strong:text-parchment-ink-strong dark:prose-strong:text-parchment-ink-strong-dark prose-em:text-parchment-ink dark:prose-em:text-parchment-ink-dark prose-a:text-parchment-ink-strong dark:prose-a:text-parchment-ink-strong-dark prose-blockquote:text-parchment-ink dark:prose-blockquote:text-parchment-ink-dark prose-blockquote:border-parchment-border dark:prose-blockquote:border-parchment-border-dark prose-ul:text-parchment-ink dark:prose-ul:text-parchment-ink-dark prose-ol:text-parchment-ink dark:prose-ol:text-parchment-ink-dark max-w-none break-words [&>p:last-child]:bg-parchment-shade dark:[&>p:last-child]:bg-parchment-shade-dark [&>p:last-child]:p-4 [&>p:last-child]:mt-6 [&>p:last-child]:rounded-md [&>p:last-child]:shadow-inner [&>p:last-child]:font-bold [&>p:last-child]:italic [&>p:last-child]:text-parchment-ink-strong dark:[&>p:last-child]:text-parchment-ink-strong-dark'
export const proseAmber =
  'prose prose-sm max-w-none dark:prose-invert text-amber-900 dark:text-amber-200 prose-p:text-amber-900 dark:prose-p:text-amber-200 prose-strong:text-amber-900 dark:prose-strong:text-amber-200 prose-headings:text-amber-900 dark:prose-headings:text-amber-200 prose-em:text-amber-900 dark:prose-em:text-amber-200 prose-a:text-amber-700 dark:prose-a:text-amber-300 prose-blockquote:text-amber-900 dark:prose-blockquote:text-amber-200 prose-blockquote:border-amber-300 dark:prose-blockquote:border-amber-700 prose-ul:text-amber-900 dark:prose-ul:text-amber-200 prose-ol:text-amber-900 dark:prose-ol:text-amber-200'
