# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "ttrpgpbp"

[api]
port = 54321
# Extra schemas to add to the search_path of every request. public is always included.
schemas = ["public", "graphql_public"]
# Extra schemas to expose in PostgREST. public is always included.
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.push-notifications]
enabled = true
verify_jwt = false
import_map = "./functions/push-notifications/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/push-notifications/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/push-notifications/*.html" ]

[auth.external.google]
enabled = true
client_id = "874851725148-ti03e8gh6mjmc5j3ddt57tku9upcm6oj.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
